import "server-only";
import { getISOWeek, parseISO } from "date-fns";
import { addLocalDays, diffLocalDays, eachLocalDay, formatLocalDate, startOfWeek, type LocalDate } from "@/domain/dates";
import { dayState, type HabitLogMap } from "@/domain/habits";
import { buildReviewText, changePct } from "@/domain/review";
import { UserFacingError } from "@/server/result";
import { getDaysInRange, type Day } from "./days";
import { getLogMaps, listHabits, toDef, type Habit } from "./habits";
import type { Settings } from "./settings";
import { listSessionsInRange, listSubjectSummaries, studySecondsByDay } from "./study";

const sleepHours = (d: Day) => (d.sleepStart && d.sleepEnd && d.sleepEnd > d.sleepStart ? (d.sleepEnd.getTime() - d.sleepStart.getTime()) / 3_600_000 : null);
const mean = (xs: number[]) => (xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : null);
const round = (x: number | null, digits = 1) => (x == null ? null : Math.round(x * 10 ** digits) / 10 ** digits);

/** Share of the week's elapsed scheduled days on which a habit succeeded. */
function weekRate(h: Habit, logs: HabitLogMap, start: LocalDate, end: LocalDate, today: LocalDate): number | null {
  let scheduled = 0;
  let ok = 0;
  for (const d of eachLocalDay(start, end)) {
    const s = dayState(toDef(h), logs, d, today);
    if (s === "off" || s === "future" || s === "pending") continue;
    scheduled++;
    if (s === "done" || s === "clear" || s === "within") ok++;
  }
  return scheduled ? ok / scheduled : null;
}

/**
 * Review for the week containing `anyDate` (default: the last completed week).
 * All numbers come straight from logs; text is generated by domain/review.ts.
 */
export async function getWeeklyReview(userId: string, anyDate: LocalDate | undefined, today: LocalDate, settings: Settings) {
  const weekStart = startOfWeek(anyDate ?? addLocalDays(startOfWeek(today, settings.weekStartsOn), -7), settings.weekStartsOn);
  if (diffLocalDays(weekStart, today) > 0) throw new UserFacingError("That week hasn’t started yet.", { week: "Pick a past or current week" });
  const weekEnd = addLocalDays(weekStart, 6);
  const prevStart = addLocalDays(weekStart, -7);
  const prevEnd = addLocalDays(weekStart, -1);

  const [study, prevStudy, sessions, subjectList, dayRows, habitList] = await Promise.all([
    studySecondsByDay(userId, weekStart, weekEnd),
    studySecondsByDay(userId, prevStart, prevEnd),
    listSessionsInRange(userId, weekStart, weekEnd),
    listSubjectSummaries(userId, { includeArchived: true }),
    getDaysInRange(userId, prevStart, weekEnd),
    listHabits(userId),
  ]);
  const logMaps = await getLogMaps(userId, habitList.map((h) => h.id), prevStart, weekEnd);

  const byDay = eachLocalDay(weekStart, weekEnd).map((date) => ({
    date,
    seconds: study.get(date) ?? 0,
    future: diffLocalDays(date, today) > 0,
    weekday: formatLocalDate(date, "EEEE"),
  }));
  const seconds = byDay.reduce((s, d) => s + d.seconds, 0);
  const prevSeconds = [...prevStudy.values()].reduce((s, v) => s + v, 0);

  const bySubject = new Map<string, number>();
  for (const s of sessions) if (s.subjectId) bySubject.set(s.subjectId, (bySubject.get(s.subjectId) ?? 0) + (s.durationSeconds ?? 0));
  const subjectTotal = [...bySubject.values()].reduce((a, b) => a + b, 0);
  const subjects = subjectList
    .filter((s) => bySubject.has(s.id) || (s.weight && !s.archivedAt))
    .map((s) => ({ id: s.id, name: s.name, seconds: bySubject.get(s.id) ?? 0, weight: s.weight }));

  const thisWeekDays = dayRows.filter((d) => d.localDate >= weekStart);
  const prevWeekDays = dayRows.filter((d) => d.localDate < weekStart);
  const sleepNow = thisWeekDays.map(sleepHours).filter((x): x is number => x != null);
  const sleepPrev = prevWeekDays.map(sleepHours).filter((x): x is number => x != null);

  // Habits on track per elapsed day, for the summary number.
  const elapsed = byDay.filter((d) => !d.future).map((d) => d.date);
  let onTrack = 0;
  let scheduled = 0;
  for (const h of habitList) {
    const logs = logMaps.get(h.id) ?? new Map();
    for (const d of elapsed) {
      const s = dayState(toDef(h), logs, d, today);
      if (s === "off" || s === "future" || s === "pending") continue;
      scheduled++;
      if (s === "done" || s === "clear" || s === "within") onTrack++;
    }
  }

  const text = buildReviewText({
    studyByDay: byDay,
    prevStudySeconds: prevSeconds,
    targetSecondsPerDay: settings.dailyStudyTargetMin * 60,
    subjects,
    habits: habitList.map((h) => {
      const logs = logMaps.get(h.id) ?? new Map();
      return { name: h.name, thisWeek: weekRate(h, logs, weekStart, weekEnd, today), prevWeek: weekRate(h, logs, prevStart, prevEnd, today) };
    }),
    sleepHours: sleepNow,
    prevSleepHours: sleepPrev,
  });

  const sleepAvg = mean(sleepNow);
  const sleepPrevAvg = mean(sleepPrev);
  return {
    weekStart,
    weekEnd,
    weekNumber: getISOWeek(parseISO(weekStart)),
    study: {
      seconds,
      targetSeconds: settings.dailyStudyTargetMin * 60 * 7,
      prevSeconds,
      changePct: changePct(seconds, prevSeconds),
      byDay: byDay.map(({ date, seconds, future }) => ({ date, seconds, future })),
    },
    consistency: { daysStudied: byDay.filter((d) => d.seconds > 0).length, days: 7 },
    habits: {
      avgPerDay: elapsed.length && scheduled ? round(onTrack / elapsed.length) : null,
      scheduledPerDay: elapsed.length && scheduled ? round(scheduled / elapsed.length) : null,
    },
    sleep: { avgHours: round(sleepAvg, 2), changeMinutes: sleepAvg != null && sleepPrevAvg != null ? Math.round((sleepAvg - sleepPrevAvg) * 60) : null },
    mood: round(mean(thisWeekDays.map((d) => d.mood).filter((x): x is number => x != null))),
    energy: round(mean(thisWeekDays.map((d) => d.energy).filter((x): x is number => x != null))),
    subjects: subjects
      .filter((s) => s.seconds > 0)
      .sort((a, b) => b.seconds - a.seconds)
      .map((s) => ({ id: s.id, name: s.name, seconds: s.seconds, share: subjectTotal ? s.seconds / subjectTotal : 0 })),
    ...text,
  };
}
